use_frameworks!

target 'BaseExtension_Example' do
  pod 'BaseExtension', :path => '../'
  pod 'RxSwift'
  pod 'RxCocoa'
  target 'BaseExtension_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.0'
        end
    end
end
