use_frameworks!

target 'BaseExtension_Example' do
  pod 'BaseExtension', :path => '../'
  pod 'RxSwift'
  pod 'RxCocoa'
  target 'BaseExtension_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
